"""update db

Revision ID: 040df99e0ab1
Revises: 135ebe52a0bb
Create Date: 2018-01-15 07:48:02.084208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '040df99e0ab1'
down_revision = '135ebe52a0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'website',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'realName',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'realName',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('company', 'website',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
