"""add company_name to company

Revision ID: 6cc7d6d7e9de
Revises: 040df99e0ab1
Create Date: 2018-01-17 07:16:41.823062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc7d6d7e9de'
down_revision = '040df99e0ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'company_name')
    # ### end Alembic commands ###
