"""add url to job

Revision ID: 7e1bff3bd909
Revises: 6cc7d6d7e9de
Create Date: 2018-01-17 07:49:13.382903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1bff3bd909'
down_revision = '6cc7d6d7e9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'url')
    # ### end Alembic commands ###
